base_url = "https://wen.is-a.dev"
title = "Wen @berserker"
description = "A simple soul in a complex system"
default_language = "en"

output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = false # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "boron"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "Notes", path = "/notes", is_external = false },
  { name = "Tags", path = "/tags", is_external = false },
  { name = "About", path = "/about", is_external = false },
  # { name = "github", path = "https://github.com/wen0x0", is_external = true },
]
blog_section_path = "/notes"

back_link_text = "Back" # Text of the back button
force_theme = false # false | "light" | "dark"

footer_copyright = "© 2025 Wen"
footer_credits = false # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"

favicon_32 = "img/favicon-32x32.png"
favicon_16 = "img/favicon-16x16.png"
apple_touch = "img/apple-touch-icon.png"