name: Deploy Zola site

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Zola
        run: |
          wget -qO- https://github.com/getzola/zola/releases/latest/download/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv zola /usr/local/bin

      - name: Build site
        run: zola build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
